kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  restartPolicy: Always
  volumes:
  - name: data
    emptyDir: {}
  initContainers:
  - name: nginx-init5
    image: docker/whalesay
    command: [sh, -c]
    args: [echo "$(cowsay -b 'Hello Kubernetes')" > /data/index.html]
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - name: nginx
    image: nginx:1.11
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html